#!/bin/bash

echo "<<<asterisk_stats>>>"
echo "sip peers $(asterisk -rx 'sip show peers' | \
                  grep "sip peers" | \
                  sed -e "s:\[Monitored\::monitored:" \
                      -e "s:Unmonitored\::unmonitored:" \
                      -e "s:\]$::")"
echo "sip users $(( $(asterisk -rx 'sip show users' | wc -l) - 1 ))"
REGS="$(asterisk -rx 'sip show registry' | wc -l)"
echo "sip registry $(asterisk -rx 'sip show registry' | \
                     tail -n$(($REGS - 1)) | \
                     head -n$(( $REGS - 2)) | \
                     sed -e "s:\s\+:\ :g" )"
echo "sip channels $(asterisk -rx 'sip show channels' | tail -n1)"
echo "sip channelstats $(asterisk -rx 'sip show channelstats' | tail -n1)"
echo "sip calls $(asterisk -rx 'core show calls' | grep active\ call | cut -d' ' -f1)"
echo "iax2 peers $(asterisk -rx 'iax2 show peers' | \
                  grep "iax2 peers" | \
                  sed -e "s:\[Monitored\::monitored:" \
                      -e "s:Unmonitored\::unmonitored:" \
                      -e "s: \[: :" \
                      -e "s:\]$::")"
