#!/bin/sh
echo "<<<openafs_fscache>>>"
[ -z "$(fs  getcacheparms -help | grep excessive)" ] && (
# OpenAFS < 1.5
fs getcacheparms | awk '{print "used " $9 " blocks " $3 " of " $8 }'
) || (
# OpenAFS >=1.5
fs getcacheparms -excessive | \
  sed -e "s:^\s*::g" -e "s:\s\+:\ :g" \
      -e "s/^AFS\ using\ [0-9]\{2\}\%\ of\ cache\ blocks\ (\([0-9]*\)\ of\ \([0-9]*\)\ \([^\s]\+\)\ blocks)/used\ \3\ blocks\ \1\ of\ \2/g" | \
  grep -e "^used " \
       -e "cache files" \
       -e "0k- 4K" \
       -e "4k- 16k" \
       -e "16k- 64k" \
       -e "64k- 256k" \
       -e "256k- 1M" \
       -e ">=1M"
)
